name: iOS build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Install node dependencies
        run: npm ci
      - name: Build with react native cli
        run: npx react-native run-ios --configuration=realease
